---
version: "3"
services:
  webserver:
    image: nginx:1.19.0
    restart: always
    hostname: webserver
    container_name: meal_client_server
    ports:
      - "8086:80"
    volumes:
      - ./build:/usr/share/nginx/html
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodeinstaller

  nodeinstaller:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - ./images/node/entrypoint.sh:/app/entrypoint.sh
      - ./build:/app/build
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: sh ./entrypoint.sh
